name: deploy-pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy site
        run: |
          docker run --rm -v ${PWD}:/docs squidfunk/mkdocs-material:8.5.3 gh-deploy --force
